export const SET_LEVELS = 'SET_LEVELS';
export const SET_CURRENT_LEVEL = 'SET_CURRENT_LEVEL';

export const FETCH_LEVELS = 'FETCH_LEVELS';

export const GET_CURRENT_LEVEL = 'GET_CURRENT_LEVEL';
export const GET_LEVELS = 'GET_LEVELS';
export const GET_CARDS_BY_CURRENT_LEVEL = 'GET_CARDS_BY_CURRENT_LEVEL';
